site_name: MeasureIt_ARCH Docs
site_url: https://kevancress.github.io/MeasureIt_ARCH/
extra_css: [extra.css]
repo_url: https://github.com/kevancress/MeasureIt_ARCH
edit_uri: edit/development/docs/docs/

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - admonition

nav:
    - Home: index.md
    - Introduction:
        - Features & UI: intro/features.md
        - FAQ: intro/faq.md

    - Tutorials:
        - Installing MeasureIt_ARCH: tutorials/install.md
        - Getting started with MeasureIt_ARCH: tutorials/getting_started.md
        - Set up a Titleblock with MeasureIt_ARCH: tutorials/titleblock_setup.md
        - Cutting Sections with MeasureIt_ARCH: tutorials/sections.md
        - Draw a Wall assembly with Dynamic Line Groups: tutorials/line_group_tut.md
        - Batch convert .svg's to .pdf's: tutorials/svg_to_pdf.md
        - Exporting to .DXF: tutorials/export_dxf.md

    - Property Descriptions:
        - Object Properties:
            - Dimensions: prop_descriptions/dimensions.md
            - Line Groups: prop_descriptions/linegroups.md
            - Annotations: prop_descriptions/annotations.md
            - Tables: prop_descriptions/tables.md
            - Hatches: prop_descriptions/hatches.md
            - Text Fields: prop_descriptions/textfields.md

        - Scene Properties:
            - Styles: prop_descriptions/styles.md
            - Units: prop_descriptions/units.md
            - Views: prop_descriptions/views.md
            - Viewports: prop_descriptions/viewports.md
            - Schedules: prop_descriptions/schedules.md
            - Settings: prop_descriptions/settings.md

        - Rendering: prop_descriptions/render.md



    - Contributions:
        - Reporting Issues: contributions/issue_reports.md
        - Requesting Features: contributions/feature_requests.md
        - Contributing Code: contributions/contributing_code.md

theme:
    name: readthedocs
    custom_dir: docs\overrides\